/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package edu.buffalo.db.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int SELECT = 10;
  /** RegularExpression Id. */
  int FROM = 11;
  /** RegularExpression Id. */
  int UNIONALL = 12;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 13;
  /** RegularExpression Id. */
  int STRING_LITERAL = 14;
  /** RegularExpression Id. */
  int NAME = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int EQ = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"%\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 9>",
    "\"SELECT\"",
    "\"FROM\"",
    "\"UNION ALL\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\".\"",
  };

}
